-- 분야별 전담 강사진.
-- 원본 시안에서는 같은 정보가 HTML 카드와 자바스크립트 DEPT 배열 두 곳에 중복으로 있었다.

create table if not exists public.coaches (
  id                   bigint generated by default as identity primary key,
  sort_order           int  not null default 0,   -- 카드 나열 순서

  name                 text not null,             -- 박○○ 코치
  photo_url            text,                      -- 프로필 사진. 없으면 화면에서 기본 이미지로 대체

  curriculum_code      text not null,             -- PILATES
  curriculum_name      text not null,             -- 축구 필라테스
  description          text not null,             -- 카드에 보이는 설명

  -- 단계 수가 강사마다 다르므로 배열로 둔다.
  -- 배열 순서가 곧 단계 번호라서 "1단계:" 같은 접두사는 저장하지 않고 화면에서 붙인다.
  steps                text[] not null default '{}',
  details              text[] not null default '{}',  -- 세부 항목

  target               text not null,             -- 대상
  recommended_sessions text not null,             -- 권장 회차
  min_duration         text not null,             -- 최소 기간
  session_format       text not null,             -- 진행 형태
  exit_criteria        text,                      -- 종료 기준. 없는 분야가 있어 비워둘 수 있다

  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);

create index if not exists coaches_sort_order_idx on public.coaches (sort_order);

-- 웹은 접속 키가 브라우저에 그대로 노출되므로 RLS 없이 두면 안 된다.
alter table public.coaches enable row level security;

-- 공개 정보라 읽기만 열어 둔다.
-- 쓰기 정책은 만들지 않으므로 외부에서는 수정할 수 없고, Supabase 대시보드에서만 관리한다.
drop policy if exists "누구나 읽기 가능" on public.coaches;
create policy "누구나 읽기 가능" on public.coaches
  for select using (true);
